<h1 style="font-size: 2em; margin: 0.67em 0px; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr</h1>
<pre style="overflow: auto; font-family: monospace, monospace; font-size: medium; padding-left: 1em; padding-right: 1em; color: #000000; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><span class="pyprompt" style="color: #aaaaaa;">&gt;&gt;&gt;</span> <span class="pyinput" style="font-weight: bold;">import angr</span>
<span class="pyprompt" style="color: #aaaaaa;">&gt;&gt;&gt;</span> <span class="pyinput" style="font-weight: bold;">proj = angr.Project('./fauxware-amd64')</span>
<span class="pyprompt" style="color: #aaaaaa;">&gt;&gt;&gt;</span> <span class="pyinput" style="font-weight: bold;">cfg = proj.analyses.CFG(); cfg.function_manager.functions</span>
<span class="pyoutput" style="color: #333333;">{4195600L: &lt;Function sub_400510 (0x400510)&gt;,
 4195616L: &lt;Function sub_400520 (0x400520)&gt;,
 4195632L: &lt;Function sub_400530 (0x400530)&gt;,
 4195648L: &lt;Function sub_400540 (0x400540)&gt;,
 4195664L: &lt;Function sub_400550 (0x400550)&gt;,
 4195680L: &lt;Function sub_400560 (0x400560)&gt;,
 4195696L: &lt;Function sub_400570 (0x400570)&gt;,
 4195712L: &lt;Function _start (0x400580)&gt;,
 4195940L: &lt;Function authenticate (0x400664)&gt;,
 4196077L: &lt;Function accepted (0x4006ed)&gt;,
 4196093L: &lt;Function rejected (0x4006fd)&gt;,
 4196125L: &lt;Function main (0x40071d)&gt;}</span>
<span class="pyprompt" style="color: #aaaaaa;">&gt;&gt;&gt;</span> <span class="pyinput" style="font-weight: bold;">ex = proj.surveyors.Explorer(find=0x4006ed).run()</span>
<span class="pyprompt" style="color: #aaaaaa;">&gt;&gt;&gt;</span> <span class="pyinput" style="font-weight: bold;">ex.found[0].state.posix.dumps(0)</span>
<span class="pyoutput" style="color: #333333;">'\x00\x00\x00\x00\x00\x00\x00\x00\x00<strong style="font-weight: 700;">SOSNEAKY</strong>\x00'</span>
</pre>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">What is angr?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr is a framework for analyzing binaries. It focuses on both static and dynamic symbolic ("concolic") analysis, making it applicable to a variety of tasks.</p>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">What's it made of?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr is made up of several subprojects, all of which are<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr">open-source!</a></p>
<ul style="padding-left: 3em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
<li>an executable and library loader,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/cle">CLE</a></li>
<li>a library describing various architectures,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/archinfo">archinfo</a></li>
<li>a Python wrapper around the binary code lifter VEX,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/pyvex">PyVEX</a></li>
<li>a VEX simulation engine,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/simuvex">SimuVEX</a></li>
<li>a data backend to abstract away differences between static and symbolic domains,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/claripy">Claripy</a></li>
<li>the full-program analysis suite itself,<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/angr">angr</a></li>
</ul>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">How has it been used academically?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">If you have used angr or its sub-components in research, please cite the paper that it was developed for:</p>
<pre style="overflow: auto; font-family: monospace, monospace; font-size: medium; padding-left: 1em; padding-right: 1em; color: #000000; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">@article{shoshitaishvili2015firmalice,
  title={Firmalice - Automatic Detection of Authentication Bypass Vulnerabilities
         in Binary Firmware},
  author={Shoshitaishvili, Yan and Wang, Ruoyu and Hauser, Christophe
          and Kruegel, Christopher and Vigna, Giovanni},
  year={2015}
}</pre>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">You can also<span class="Apple-converted-space">&nbsp;</span><em>read</em><span class="Apple-converted-space">&nbsp;</span>the paper<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="http://www.internetsociety.org/doc/firmalice-automatic-detection-authentication-bypass-vulnerabilities-binary-firmware">here</a>!</p>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">And non-academically?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr was one of the underpinnings of Shellphish's Cyber Reasoning System for the DARPA Cyber Grand Challenge, enabling them to qualify for the CGC finals!</p>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Whom can I contact?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">If you have questions with a subcomponent of angr, please open an issue on github (or send us a pull request!). If you have questions or comments, drop us a line at the mailing list at<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="mailto:angr@lists.cs.ucsb.edu">angr@lists.cs.ucsb.edu</a>.</p>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Who works on angr?</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr is worked on by several researchers in the<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="http://seclab.cs.ucsb.edu/">Computer Security Lab at UC Santa Barbara</a>. Major contributers (arbirtrarily, 1000+ lines of code!) include:</p>
<ul style="padding-left: 3em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
<li>Yan Shoshitaishvili</li>
<li>Andrew Dutcher</li>
<li>Ruoyu (Fish) Wang</li>
<li>Christophe Hauser</li>
<li>John Grosen</li>
<li>Chris Salls</li>
</ul>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">angr owes its existence to research sponsored by DARPA under agreement number<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="http://www.darpa.mil/program/vetting-commodity-it-software-and-firmware">N66001-13-2-4039</a>!</p>
<h2 style="margin-top: 1.5em; margin-bottom: -0.3em; color: #000000; font-family: sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">How can I help</h2>
<p style="padding-left: 1em; padding-right: 1em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">There are many ways to participate! Here are some ideas:</p>
<ul style="padding-left: 3em; color: #000000; font-family: sans-serif; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
<li>Report bugs. We know they exist, but it's not always clear where they are!</li>
<li>Write documentation. An analysis system like angr can be a bit overwhelming. If you're using it, and could send a pull request for our<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/angr-doc">documentation repo</a>, we would be eternally grateful! This includes examples -- if you use angr for something cool, send us a pull request with an example!</li>
<li>Implement more environment support. We use the concept of "function summaries" in angr to model the environment of operating systems (i.e., the effects of their system calls) and library functions. Extending this would be greatly helpful in increasing angr's utility. These function summaries can be found<span class="Apple-converted-space">&nbsp;</span><a style="background-color: transparent;" href="https://github.com/angr/simuvex/tree/master/simuvex/procedures">here</a>.</li>
</ul>
